
version: '3.8'
services:
  springboot-app:
    container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8000:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_PORT: 3306
      REDIS_PORT: 6379
      REDIS_HOST: myredis
    networks:
      - my_network

  redis:
    image: redis
    container_name: myredis
    command: redis-server
    hostname: myredis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - my_network

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: mysecretpassword
    networks:
      - my_network

networks:
  my_network:

